name: Download Translations

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Translations from Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'Daily Translation Update'
          pull_request_body: 'Daily translation updates downloaded by [Crowdin GH Action](https://github.com/crowdin/github-action).'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

          - name: Get Pull Request Number
          id: get_pr
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GH_TOKEN }}
            script: |
              const { data: pullRequests } = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: 'open',
                head: `${context.repo.owner}:l10n_crowdin_translations`,
              });
              if (pullRequests.length > 0) {
                core.setOutput("result", pullRequests[0].number);
              } else {
                core.setFailed("No pull request found for the l10n_crowdin_translations branch.");
              }
        
        - name: Merge Pull Request
          if: success()  # 如果上一步骤成功才继续
          uses: actions/github-script@v6
          with:
            github-token: ${{ secrets.GH_TOKEN }}
            script: |
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: ${{ steps.get_pr.outputs.result }},
                commit_title: '[skip-upload] Auto-merge Crowdin translations',
                merge_method: 'squash',
              });        
