name: Download Translations

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download-and-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Translations from Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'Daily Translation Update'
          pull_request_body: 'Daily translation updates downloaded by [Crowdin GH Action](https://github.com/crowdin/github-action).'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Get Pull Request Number
        id: get_pr
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:l10n_crowdin_translations`,
            });
            if (pullRequests.length > 0) {
              console.log("Found PR number:", pullRequests[0].number);
              return pullRequests[0].number;  // 直接返回数字
            } else {
              core.setFailed("No pull request found for the l10n_crowdin_translations branch.");
              return null;
            }

      - name: Merge Pull Request
        if: steps.get_pr.outputs.result != ''  # 确保有 PR 编号才执行
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const pullNumber = ${{ steps.get_pr.outputs.result }};  // 直接使用数字
            console.log("Pull Request Number:", pullNumber);
            if (!pullNumber) {
              throw new Error("Pull Request number is not defined");
            }
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              commit_title: '[skip-upload] Auto-merge Crowdin translations',
              merge_method: 'squash'
            });